apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-platform

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  environment: staging
  app.kubernetes.io/environment: staging

patches:
  - path: resource-patch.yaml
    target:
      kind: ResourceQuota
      name: ml-platform-quota

images:
  - name: gcr.io/fb-ads-ml/user-persona
    newTag: staging-latest
  - name: gcr.io/fb-ads-ml/autobid
    newTag: staging-latest
